services:
  snid_api:
    build: ./snid_docker/
    cpus: 2
    expose:
      - "8000"
    environment:
      DJANGO_URL: http://web:8000
    volumes:
      - /mnt/api_results/snid_api_runs:/snid_api_runs
      #- spectra_volume:/data/spectra:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 2s
    #networks:
    #  - backend

  ngsf_api:
    build: ./ngsf_docker/
    cpus: 2
    expose:
      - "8000"
    environment:
      DJANGO_URL: http://web:8000
    volumes:
      - /mnt/api_results/ngsf_api_runs:/ngsf_api_runs
      #- spectra_volume:/data/spectra:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 2s
    #networks:
    #  - backend
#volumes:
#  snid_api_runs:
#    external: true
#  ngsf_api_runs:
#    external: true
#  media_volume:
#    external: true

#networks:
#  backend:
#    external: true
